/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BtnThreads: typeof import('./src/components/ui/BtnThreads.vue')['default']
    Button: typeof import('primevue/button')['default']
    IconLogo: typeof import('./src/components/icons/IconLogo.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Password: typeof import('primevue/password')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('primevue/sidebar')['default']
    Test: typeof import('./src/components/ui/Test.vue')['default']
  }
}
